<?php
namespace cvsoft\profiler\profiling;


class HttpProfiler extends AbstractProfiler
{
    /**
     * Определяет наличие в сессии ключа текущего профиля и при возможности загружает его
     * @return null
     */
    public static function loadFromSession()
    {
        return parent::loadFromSession(); // TODO: Change the autogenerated stub
    }
}
